Fixed a `KeyError` in the Python Client SDK's vfolder `mkdir` command, caused by a missing "results" key in the API response
